#
# ansible playbook
#
# CONFIGURE K0CDF-K8S-PI cluster
#
---

- name: install packages
  become: yes
  hosts: all
  tasks:
  - name: apt update
    ansible.builtin.apt:
      update_cache: yes
  - name: apt upgrade
    ansible.builtin.apt:
      upgrade: yes 
  - name: apt install python
    ansible.builtin.apt:
      name:
      - python3
      - python3-pip
  - name: install python packages
    ansible.builtin.pip:
      name:
      - ansible

# stolen from https://github.com/geerlingguy/raspberry-pi-dramble/blob/master/tasks/cgroup-features.yml
- name: cgroups stuff
  become: yes
  tasks:
  - name: Enable required cgroup features.
    lineinfile:
      path: /boot/cmdline.txt
      backrefs: True
      regexp: '(^.+rootwait(\s+(?!cgroup_enable=cpuset cgroup_enable=memory)[\w=/\-\.]+)*)\s*$'
      line: '\1 cgroup_enable=cpuset cgroup_enable=memory'
      state: present
    register: cgroup_features
    when: deploy_target == 'pi'

  - name: Reboot immediately if cgroup features changed.
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0
    when: cgroup_features is changed

  - name: Wait for the reboot to complete if cgroup features changed.
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300
    when: cgroup_features is changed
  # end stolen

  # stolen from https://github.com/geerlingguy/raspberry-pi-dramble/blob/master/tasks/disable-swap.yml
- name: swap disable
  become: yes
  tasks:
  - name: Disable swap.
    shell: >
      dphys-swapfile swapoff &&
      dphys-swapfile uninstall &&
      update-rc.d -f dphys-swapfile remove
    when:
      - ansible_swaptotal_mb > 0
      - deploy_target == 'pi'
# end stolen

- name: microk8s setup
  become: yes
  tasks: 
# https://github.com/mike-matera/cis-infrastructure/blob/master/ansible/roles/microk8s/tasks/main.yaml#L34
  - name: install microk8s with snap
    become: yes
    community.general.snap:
      name: microk8s
      state: present
      classic: yes

# https://github.com/mike-matera/cis-infrastructure/blob/master/ansible/roles/microk8s/tasks/main.yaml#L40
  - name: Add the user to microk8s
    user:
      name: "{{ ansible_user_id }}"
      groups: microk8s
      append: yes

- name: start microk8s
  tasks:

# https://github.com/mike-matera/cis-infrastructure/blob/master/ansible/roles/microk8s/tasks/main.yaml#L46
  - name: Reset SSH to allow ubuntu int microk8s group.
    meta: reset_connection

# https://github.com/mike-matera/cis-infrastructure/blob/master/ansible/roles/microk8s/tasks/main.yaml#L49
  - name: Start microk8s
    shell: /snap/bin/microk8s start 

# https://github.com/mike-matera/cis-infrastructure/blob/master/ansible/roles/microk8s/tasks/main.yaml#L52
  - name: Wait for microk8s
    shell: /snap/bin/microk8s status --wait-ready 


# inspired by https://github.com/mike-matera/cis-infrastructure/blob/master/ansible/student-cluster.yaml
# inspired by https://github.com/mike-matera/cis-infrastructure/blob/master/ansible/roles/microk8s-add-node/tasks/main.yaml

- name: create cluster key on pi-1 for pi-2
  hosts: k0cdf-k8s-pi-1
  become: yes
  tasks:
  - name: generate join key for pi 2 on pi 1
    shell: /snap/bin/microk8s add-node | grep "microk8s join" | head -n 1
    register: microk8s_join_key

- name: join pi-2 to pi-1
  hosts: k0cdf-k8s-pi-2
  become: yes
  tasks:
  - name: apply join key on pi 2
    shell: "/snap/bin/{{ hostvars['k0cdf-k8s-pi-1']['microk8s_join_key'].stdout }} || /bin/true"

- name: create cluster key on pi-1 for pi-3
  hosts: k0cdf-k8s-pi-1
  become: yes
  tasks:
  - name: generate join key for pi 3 on pi 1
    shell: /snap/bin/microk8s add-node | grep "microk8s join" | head -n 1
    register: microk8s_join_key

- name: join pi-3 to pi-1
  hosts: k0cdf-k8s-pi-3
  become: yes
  tasks:
  - name: apply join key on pi 3
    shell: "/snap/bin/{{ hostvars['k0cdf-k8s-pi-1']['microk8s_join_key'].stdout }} || /bin/true"
# end inspired
# end inspired

- name: alias setup
  tasks:
  - name: alias kubectl to mikrok8s.kubectl
    blockinfile:
      path: /home/ciaran/.bash_alias
      create: yes
      block: |
        alias kubectl="microk8s.kubectl"

# inspired by https://github.com/mike-matera/cis-infrastructure/blob/master/ansible/roles/microk8s/tasks/main.yaml#L55

- name: enable kube addons
  tasks:
  - name: Enable Helm v3
    shell: /snap/bin/microk8s enable helm3

  - name: Enable kube dns.
    shell: /snap/bin/microk8s enable dns 

  - name: Enable MetalLB
    shell: /snap/bin/microk8s enable metallb "10.156.98.185-10.156.98.190"

  - name: Enable Ingress
    shell: /snap/bin/microk8s enable ingress 

  - name: Enable dashboard
    shell: /snap/bin/microk8s enable dashboard 

