# /ansible_playbook.yml
#
# main ansible playbook file
#
# Copyright (C) 2022  Ciaran Farley
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# K0CDF Ciaran Farley
# 228 16th Ave. Santa Cruz CA 95062.
# cq@k0cdf.us
#
---


- name: run apt maintinace on PVE hosts
  hosts: PVE
  roles:
    - apt-maintinance


- name: create nginxproxymanager container
  hosts: k0cdf-srv1-pve1
  vars:
    pve_ct_id: '150'
    pve_ct_hostname: 'k0cdf-srv1-srv'
    pve_ct_ip: '10.30.15.50'
  roles:
    - create-ct


- name: create snipe it container
  hosts: k0cdf-srv1-pve1
  vars:
    pve_ct_id: '151'
    pve_ct_hostname: 'k0cdf-srv1-snipeit'
    pve_ct_ip: '10.30.15.51'
  roles:
    - create-ct





- name: install snipe-it
  hosts: k0cdf-srv1-snipeit
  tasks:
    - name: apt maintinance on snipe-it
      ansible.builtin.include_role:
        name: apt-maintinance

    - name: Install and Configure Snipe-IT
      ansible.builtin.include_role: 
        name: wiggels.snipeit
      vars:
        - snipe_domain: k0cdf-srv1-snipeit.local.mesh
        - snipe_app_timezone: America/Los_Angeles
        - snipe_db_password: k0cdf
