#
# ansible playbook
#
# configure local machine for cluster access and configure cluster machines
#
---

- name: local setup
  local_action:
  tasks:
    -name: generate ssh keypair for use with k8s hosts
      community.crypto.openssh_keypair:
        path: $(HOME)/.ssh/k0cdf_k8s_key

- name: credentials setup
  hosts: all
  tasks:
    - name: copy credentials to nodes
      ansible.posix.authorized_key:
       key: $(HOME)/.ssh/k0cdf_k8s_key.pub
       user: ubuntu

- name: install depedances
  hosts: all
  Tasks:
    