#
# ansible playbook
#
# configure local machine for cluster access and configure cluster machines
#
---

- name: setup local ssh keys for cluster
  local_action:
    community.crypto.openssh_keypair:
      path: $(HOME)/.ssh/k0cdf_k8s_key

- name: copy key to k8s hosts
  hosts: all
    ansible.posix.authorized_key:
      key: $(HOME)/.ssh/k0cdf_k8s_key.pub
      user: ubuntu