#
# ansible playbook
#
# configure local machine for cluster access and configure cluster machines
#
---

# stolen from https://github.com/geerlingguy/raspberry-pi-dramble/blob/master/tasks/cgroup-features.yml
- name: Enable required cgroup features.
  lineinfile:
    path: /boot/cmdline.txt
    backrefs: True
    regexp: '(^.+rootwait(\s+(?!cgroup_enable=cpuset cgroup_enable=memory)[\w=/\-\.]+)*)\s*$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory'
    state: present
  register: cgroup_features
  when: deploy_target == 'pi'

- name: Reboot immediately if cgroup features changed.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: cgroup_features is changed

- name: Wait for the reboot to complete if cgroup features changed.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: cgroup_features is changed
# end stolen

# stolen from https://github.com/geerlingguy/raspberry-pi-dramble/blob/master/tasks/disable-swap.yml
- name: Disable swap.
  shell: >
    dphys-swapfile swapoff &&
    dphys-swapfile uninstall &&
    update-rc.d -f dphys-swapfile remove
  when:
    - ansible_swaptotal_mb > 0
    - deploy_target == 'pi'
# end stolen

- name: install microk8s with snap
  become: yes
  community.general.snap:
    name: microk8s
    state: present
    classic: yes

# inspired by https://github.com/mike-matera/cis-infrastructure/blob/master/ansible/roles/microk8s-add-node/tasks/main.yaml
# inspired by https://github.com/mike-matera/cis-infrastructure/blob/master/ansible/student-cluster.yaml

- name: create cluster key on pi-1 for pi-2
  hosts: k0cdf-k8s-pi-1
  become: yes
  shell: /snap/bin/microk8s add-node | grep "microk8s join" | head -n 1
  register: microk8s_join_key

- name: join pi-2 to pi-1
  hosts: k0cdf-k8s-pi-2
  become: yes
  shell: "/snap/bin/{{ hostvars['k0cdf-k8s-pi-1']['microk8s_join_key'].stdout }} || /bin/true"

- name: create cluster key on pi-1 for pi-3
  hosts: k0cdf-k8s-pi-1
  become: yes
  shell: /snap/bin/microk8s add-node | grep "microk8s join" | head -n 1
  register: microk8s_join_key

- name: join pi-3 to pi-1
  hosts: k0cdf-k8s-pi-3
  become: yes
  shell: "/snap/bin/{{ hostvars['k0cdf-k8s-pi-1']['microk8s_join_key'].stdout }} || /bin/true"

- name: alias kubectl to mikrok8s.kubectl
  blockinfile:
    path: /home/ciaran/.bash_alias
    create: yes
    block: |
      alias kubectl="microk8s.kubectl"

