#
# ansible playbook
# 
# configure k0cdf-maas
#
---

- name: install packages
  become: yes
  hosts: all
  tasks:
  - name: apt update
    ansible.builtin.apt:
      update_cache: yes
  - name: apt upgrade
    ansible.builtin.apt:
      upgrade: yes
  - name: snap install maas
    community.general.snap:
      name: maas
  - name: apt install postgres
    ansible.builtin.apt:
      name: postgresql

- name: configure postgres
  become: yes
  hosts: all
  tasks:
  - name: create postgres user for maas
    community.postgresql.postgresql_user:
      name: maasuser
      password: maas123
  - name: create postgres database
    community.postgresql.postgresql_db:
      name: maas
  - name: postgres grant permissions
    community.postgresql.postgresql_privs:
      database: maas
      roles: maasuser
      type: database
      privs: all