#
# ansible playbook
# 
# configure k0cdf-maas
#
---

- name: install packages
  become: yes
  hosts: k0cdf-maas
  tags: packages
  tasks:

  - name: apt update
    ansible.builtin.apt:
      update_cache: yes

  - name: apt upgrade
    ansible.builtin.apt:
      upgrade: yes

  - name: snap install packages
    community.general.snap:
      name: 
      - maas

  - name: apt install packages
    ansible.builtin.apt:
      name: 
      - acl
      - postgresql
      - libpq-dev
      - python3-pip
      - python3-psycopg2

  - name: pip install packages
    ansible.builtin.pip:
      name:
      - psycopg2
  
  - name: reboot
    ansible.builtin.reboot:
    


- name: configure postgres
  become: true
  become_user: postgres
  hosts: k0cdf-maas
  tasks:

  - name: create postgres user for maas
    community.postgresql.postgresql_user:
      name: maasuser
      password: maas123

  - name: create postgres database
    community.postgresql.postgresql_db:
      name: maas

  - name: postgres grant permissions
    community.postgresql.postgresql_privs:
      database: maas
      roles: maasuser
      type: database
      privs: all



- name: configure maas
  become: true
  hosts: k0cdf-maas
  tasks:

  - name: pg hba config
    ansible.builtin.lineinfile:
      path: /etc/postgresql/12/main/pg_hba.conf
      line: host maas maaszeljko 0/0 md5

  - name: maas init
    ansible.builtin.shell:
      cmd: maas init region+rack --database-uri "postgres://maasuser:maas123@localhost/maas"

  - name: maas createadmin
    ansible.builtin.shell:
      cmd: maas createadmin --username ciaran --password k0cdf73 --email cq@k0cdf.us --ssh-import gh:cTurtle98
